import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AppContextProvider } from "@/context/Provider";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const activePath = headersList.get("x-pathname");
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          {activePath}
          <Header />
          {children}
          {/* <Footer /> */}
        </AppContextProvider>
      </body>
    </html>
  );
}
